// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6tBHH_uYvBLwBD3dlNPKucyvQhYF6vec',
    appId: '1:647858293339:android:e5c0076872d541c9e8cd7e',
    messagingSenderId: '647858293339',
    projectId: 'contatto-895d3',
    storageBucket: 'contatto-895d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPiFlHUvuehIpSzgU8ttKrzR_GJpIcC2k',
    appId: '1:647858293339:ios:724a86d19c0208a8e8cd7e',
    messagingSenderId: '647858293339',
    projectId: 'contatto-895d3',
    storageBucket: 'contatto-895d3.appspot.com',
    iosClientId: '647858293339-edf7bs9ntmvjii05dmf6dda1sotpa5t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appContatto',
  );
}
